### PR TITLE
Fixes register=false. Changed src to ng-src

### PR DESCRIPTION
**Pull request by erikmellum**
These bugs were breaking everything for me. Hope it helps others, angular-spinners is neat!

### CODE REVIEW

**Comment by AlexAllocated** [comment]
Thanks for the updates. Can you tell me how `if ($scope.register)` was breaking for you? I'm just curious.

**Comment by erikmellum** [comment]
Basically if you set register=false on the spinner directive, it was still registering the spinner service for me. My guess is because if(register) is an undefined check rather than a boolean check (that is an inference by me, I'm not a javascript expert I was just using empirical evidence).

**Comment by AlexAllocated** [comment]
That's strange. The expression should have evaluated to false if set to `false`, `undefined`, or `null`. My next big step is to add unit tests to the project so we can keep things in working order. Hopefully that helps resolve some of these edge cases.

Regardless, I should be doing explicit conditionals anyway :)

Thanks again.

**Comment by AlexAllocated** [comment]
Ohhhh, it's because the `false` value is a damn string! Oh Javascript, we have a love/hate relationship you and I.

**Comment by erikmellum** [comment]
Yeah..... that makes so much sense now. Glad you solved it :). I actually am running into a problem - perhaps you can help?

Basically I have a list of projects that are displayed with ng-repeat. Each project has a spinner. When I create a new project, it adds a project to the ng-repeat (including the spinner). I'm running into a problem where it calls spinnerService.show in my "createProject" function BEFORE the _register function gets fired off for the newly added project spinner. Do you have any tips on how to resolve this? My instinct screams promises, but I've never really used them. I hate asking rather than figuring it out, no worries if my use case is too specific!

**Comment by AlexAllocated** [comment]
That's what [onLoaded](https://github.com/codetunnel/angular-spinners#onloaded) is for :)

**Comment by erikmellum** [comment]
Hooray!

**Comment by AlexAllocated** [comment]
The final fix for this directive type weirdness is published in version 2.1.8 btw :)

It now explicitly converts the `register` property to a boolean if it's present.

**Comment by AlexAllocated** [comment]
PS - You can also supply `show="true"` to show the spinner by default when it's added to the DOM. It will show itself even before it has registered with the service.

``` html
<spinner name="mySpinner" show="true"></spinner>
```

`show` is also two-way bound so you can supply a scope variable and toggle the spinner on/off that way instead, if needed.

``` html
<spinner name="mySpinner" show="loading"></spinner>
<button ng-click="loading = !loading">Toggle Loading</button>
```

**Comment by erikmellum** [comment]
Okay so I had some problems with getting the on-loaded function to work. In fact, I gave up and used $timeout. Apparently $timeout requires the dom to be properly loaded to execute. The code below accomplished what on-loaded would have probably been a better choice for.

createProject=function(){
...
callback=function(){
//project done loading
$timeout(function () {
   spinnerService.hide(projectName + 'spinner');
 });
}
$timeout(function () {
   spinnerService.show(projectName + 'spinner');
 });
}

I'd love to know what I was doing wrong with on-loaded, plus it seems like you want it to be as easy to use as possible. Maybe I'm a good test subject in some regards! My on-loaded coded was identical to your snippets in the docs. Oh, and thank YOU for making this spinner!

**Comment by AlexAllocated** [comment]
Don't use a timeout. By doing that you are creating what's called a [race condition](https://en.wikipedia.org/wiki/Race_condition). You are depending on the fact that your timer will always fire _after_ the spinner has registered. Even if that's true in your current setup, there are tons of things that could easily throw that out of whack and cause the bug to reappear.

I would need some more of your code to truly be able to tell you what you were doing wrong, but using `onLoaded` should look something like this:

``` html
<spinner name="mySpinner" on-loaded="spinnerLoaded()"></spinner>
```

``` javascript
app.controler('myCtrl', function ($scope, spinnerService) {
  $scope.spinnerLoaded = function () {
    // spinner is now loaded and registered with the spinner service
    spinnerService.show('mySpinner');
  };
});
```

The `onLoaded` option expects an [Angular Expression](https://docs.angularjs.org/guide/expression). That expression has access to two variables if you want them. The first one is `spinnerService` and is the same service you would typically inject into your controllers. The second one is `spinnerApi` which is [the little API object created by the directive and handed off to the service](https://github.com/codetunnel/angular-spinners/blob/6cdf22778fca46e22f6c42fa0927281e420b5043/src/spinner-directive.js#L34-L46).

``` html
<spinner name="mySpinner" on-loaded="spinnerLoaded(spinnerApi)"></spinner>
```

``` javascript
app.controller('myCtrl', function ($scope) {
  $scope.spinnerLoaded = function (mySpinner) {
    mySpinner.show();
  };
});
```

Any logic you do inside the `onLoaded` expression will run _after_ the spinner has registered with the service so both of the above methods work just fine. Manually getting reference to that spinner's API isn't a common thing to do but it's there for convenience, usually for the edge cases where you need to set `register` to `false` because you can still get reference to the spinner's API manually and control it that way.

**Comment by AlexAllocated** [comment]
Here's a working demo of `onLoaded`: http://codepen.io/Chevex/pen/NqwzjN

Don't forget what I said above. You can also just show the spinner by default as soon as it's on the page.

``` html
<spinner name="mySpinner" show="true"></spinner>
```

Or by supplying a boolean to `show`.

``` html
<spinner name="mySpinner" show="dataLoaded"></spinner>
```

Neither of the above examples require the spinner to be registered with the service so they will work even before the spinner finally registers itself.

**Comment by erikmellum** [comment]
Hmm that is so strange! Your code on the codepen is working perfectly but for some reason my on-loaded function never executes. I can't locate any difference in what I am doing vs what you are doing. I will figure it out and update you when I do. In the meantime... this is the code!

```
<html lang="en" ng-app="application">
<body ng-controller="ProjectCtrl">
 <ul>
   <li ng-class="{active: ($index == activeProject.index)}" ng-click="setActiveProject(project, $index)" ng-repeat="project in projects" ui-sref-active="is-active">
     <spinner class="float-right" on-loaded="spinnerLoaded(spinnerApi)" name="{{project.name}}spinner" img-src="assets/img/spinner.gif"></spinner>
   </li>
</ul>
</body>
</html>


 var application = angular.module('application', [
'ui.router',
'ngAnimate',
'controllers',
'directives',
'services',
'foundation'
 ])
application.controller('ProjectCtrl', ['$scope', '$timeout', 'FoundationApi', 'spinnerService',  function($scope, $timeout, foundationApi, spinnerService) {
 $scope.spinnerLoaded = function (mySpinner) {
       console.log("onload");
       mySpinner.show();
    };
}
```

**Comment by AlexAllocated** [comment]
You don't have "angularSpinners" in your angular app dependencies.

**Comment by AlexAllocated** [comment]
``` javascript
var application = angular.module('application', [
  'ui.router',
  'ngAnimate',
  'controllers',
  'directives',
  'services',
  'foundation',
  'angularSpinners'
]);
```

**Comment by erikmellum** [comment]
Yeah that was the problem. I was actually adding all of it in via the blog post which is deprecated compared to the bower version. Thanks for all your help. Its working now.

**Comment by AlexAllocated** [comment]
I'm glad :)

I actually updated the blog post a few days ago from start to finish so that it now matches what my spinner pattern has evolved into recently. Other than the fact that it's offered as a bower package, that post should be nearly identical to what the bower package provides. Do let me know if there is a discrepancy still. Maybe you hadn't seen the post since I updated it?

**Comment by erikmellum** [comment]
It looks like there is a discrepancy specifically with the onLoaded, onShow, and onHide functionality. 
http://prntscr.com/7kzzaj

Glad to help!

**Comment by AlexAllocated** [comment]
Well `onShow` and `onHide` were added last night. I'll be sure to work them into the post. `onLoaded` must still be referred to as `onRegister` in the post so I'll fix that when I get to a computer. Thanks!

**Comment by erikmellum** [comment]
That makes sense! I should have noticed that register=load when I was error checking. I learned some cool angular functionality from your code patterns, plus I needed spinners so win win. Keep up the great work!

**Pull request merged**
